# .releaserc.yml

# Plugin configurations
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - ['@semantic-release/git', {
      assets: [
        'CHANGELOG.md',
        'package.json',
        'package-lock.json',
        'pdf/*.pdf' # File glob pattern for PDF files
      ]
    }]
# Branches to release from
branches:
  - main
  - next
  - next-major
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

# Configuration for @semantic-release/commit-analyzer
# Determines the type of release (major, minor, or patch) based on commit messages.
# Learn more: https://github.com/semantic-release/commit-analyzer
commit-analyzer:
  preset: conventionalcommits

# Configuration for @semantic-release/release-notes-generator
# Generates release notes based on commit messages.
# Learn more: https://github.com/semantic-release/release-notes-generator
release-notes-generator:
  preset: conventionalcommits

# Configuration for @semantic-release/git
# Commits the version change and release notes to the Git repository.
# Learn more: https://github.com/semantic-release/git
git:
  assets:
    - CHANGELOG.md
    - package.json
    - docs
    - docs/*.pdf
  message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

# Configuration for @semantic-release/github
# Publishes the release to GitHub.
# Learn more: https://github.com/semantic-release/github
github:
  release: true
