---
name: CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  call-build-workflow:
    name: Docs to PDF
    uses: ./.github/workflows/cd-build.yaml
  call-publish-workflow:
    name: Publish docs via GitHub Pages
    uses: ./.github/workflows/cd-publish.yaml
  call-release-workflow:
    name: Release
    needs:
      - call-build-workflow
    uses: ./.github/workflows/cd-release.yaml
    secrets: inherit
